In [ ]:
1:
    
Yes, there is a difference in the data type of list_ and array_list...

list_ is a Python list containing string elements,
whereas array_list is a NumPy array containing Unicode string elements.

import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print(type(list_))
print(type(array_list))

#Output:
<class 'list'>
<class 'numpy.ndarray'>


This code imports the NumPy library, creates a Python list called list_ containing
five string elements, and then creates a NumPy array called array_list from
the list_ using the np.array function. 

    The object argument specifies the Python list to be converted to a NumPy
array. Finally, the code prints the data types of both variables using the 
type() function.
    
    
    
    
    
    
    
    

In [ ]:
2:
Code that prints the data type of each element in list_ and array_list:
    
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Printing data type of each element in list_
for element in list_:
    print(type(element))

# Printing data type of each element in array_list
for element in array_list:
    print(type(element))
  
    
    
#Output:

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>

    
    
    
    
    
    

In [ ]:
3:
Yes, there will be a difference in the data type of the elements present in
both the variables list_ and array_list.

When the np.array function is called with the dtype=int argument, the elements
in the list_ variable will be converted to integers and stored as int data 
type in the resulting array_list.
    
    
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data type of each element in list_
for element in list_:
    print(type(element))

# Print data type of each element in array_list
for element in array_list:
    print(type(element))

#Output:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


    
    
    
    
    

In [ ]:
4:
    
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# Find the shape of num_array
print(num_array.shape)

# Find the size of num_array
print(num_array.size)
    
    
#Output:

(2, 3)
6

    
    
    
    
    
    

In [ ]:
5:
    
import numpy as np

zeros_array = np.zeros((3, 3))
print(zeros_array)


#Output:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


    

In [ ]:
6:
    
A code to create an identity matrix of shape (5, 5) using numpy functions:

import numpy as np

identity_matrix = np.zeros((5, 5))
identity_matrix[np.diag_indices(5)] = 1

print(identity_matrix)

    
#Output:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]




    
    
    
    
    
    